export const UPDATE_FBCONFIG_SUCCESS = 'UPDATE_FBCONFIG_SUCCESS'
export const UPDATE_FBCONFIG_ERROR = 'UPDATE_FBCONFIG_ERROR'
export const GET_FBCONFIG_ERROR = 'GET_FBCONFIG_ERROR'
export const GET_FBCONFIG_SUCCESS = 'GET_FBCONFIG_SUCCESS'

export const UPDATE_GOOGLEMYBUSINESSCONFIG_SUCCESS = 'UPDATE_GOOGLEMYBUSINESSCONFIG_SUCCESS'
export const UPDATE_GOOGLEMYBUSINESSCONFIG_ERROR = 'UPDATE_GOOGLEMYBUSINESSCONFIG_ERROR'
export const GET_GOOGLEMYBUSINESSCONFIG_SUCCESS = 'GET_GOOGLEMYBUSINESSCONFIG_SUCCESS'
export const GET_GOOGLEMYBUSINESSCONFIG_ERROR = 'GET_GOOGLEMYBUSINESSCONFIG_ERROR'


export const UPDATE_INSTAGRAMCONFIG_SUCCESS = 'UPDATE_INSTAGRAMCONFIG_SUCCESS'
export const UPDATE_INSTAGRAMCONFIG_ERROR = 'UPDATE_INSTAGRAMCONFIG_ERROR'
export const GET_INSTAGRAMCONFIG_SUCCESS = 'GET_INSTAGRAMCONFIG_SUCCESS'
export const GET_INSTAGRAMCONFIG_ERROR = 'GET_INSTAGRAMCONFIG_ERROR'


export const UPDATE_LINKEDINCONFIG_SUCCESS = 'UPDATE_LINKEDINCONFIG_SUCCESS'
export const UPDATE_LINKEDINCONFIG_ERROR = 'UPDATE_LINKEDINCONFIG_ERROR'
export const GET_LINKEDINCONFIG_SUCCESS = 'GET_LINKEDINCONFIG_SUCCESS'
export const GET_LINKEDINCONFIG_ERROR = 'GET_LINKEDINCONFIG_ERROR'


export const UPDATE_ODNOKLASNIKICONFIG_SUCCESS = 'UPDATE_ODNOKLASNIKICONFIG_SUCCESS'
export const UPDATE_ODNOKLASNIKICONFIG_ERROR = 'UPDATE_ODNOKLASNIKICONFIG_ERROR'
export const GET_ODNOKLASNIKICONFIG_SUCCESS = 'GET_ODNOKLASNIKICONFIG_SUCCESS'
export const GET_ODNOKLASNIKICONFIG_ERROR = 'GET_ODNOKLASNIKICONFIG_ERROR'


export const UPDATE_PINTERESTCONFIG_SUCCESS = 'UPDATE_PINTERESTCONFIG_SUCCESS'
export const UPDATE_PINTERESTCONFIG_ERROR = 'UPDATE_PINTERESTCONFIG_ERROR'
export const GET_PINTERESTCONFIG_SUCCESS = 'GET_PINTERESTCONFIG_SUCCESS'
export const GET_PINTERESTCONFIG_ERROR = 'GET_PINTERESTCONFIG_ERROR'


export const UPDATE_REDDITCONFIG_SUCCESS = 'UPDATE_REDDITCONFIG_SUCCESS'
export const UPDATE_REDDITCONFIG_ERROR = 'UPDATE_REDDITCONFIG_ERROR'
export const GET_REDDITCONFIG_SUCCESS = 'GET_REDDITCONFIG_SUCCESS'
export const GET_REDDITCONFIG_ERROR = 'GET_REDDITCONFIG_ERROR'


export const UPDATE_TUMBLRCONFIG_SUCCESS = 'UPDATE_TUMBLRCONFIG_SUCCESS'
export const UPDATE_TUMBLRCONFIG_ERROR = 'UPDATE_TUMBLRCONFIG_ERROR'
export const GET_TUMBLRCONFIG_SUCCESS = 'GET_TUMBLRCONFIG_SUCCESS'
export const GET_TUMBLRCONFIG_ERROR = 'GET_TUMBLRCONFIG_ERROR'


export const UPDATE_TWITTERCONFIG_SUCCESS = 'UPDATE_TWITTERCONFIG_SUCCESS'
export const UPDATE_TWITTERCONFIG_ERROR = 'UPDATE_TWITTERCONFIG_ERROR'
export const GET_TWITTERCONFIG_SUCCESS = 'GET_TWITTERCONFIG_SUCCESS'
export const GET_TWITTERCONFIG_ERROR = 'GET_TWITTERCONFIG_ERROR'


export const UPDATE_VIKONTAKTECONFIG_SUCCESS = 'UPDATE_VIKONTAKTECONFIG_SUCCESS'
export const UPDATE_VIKONTAKTECONFIG_ERROR = 'UPDATE_VIKONTAKTECONFIG_ERROR'
export const GET_VIKONTAKTECONFIG_SUCCESS = 'GET_VIKONTAKTECONFIG_SUCCESS'
export const GET_VIKONTAKTECONFIG_ERROR = 'GET_VIKONTAKTECONFIG_ERROR'


export const UPDATE_YOUTUBECONFIG_SUCCESS = 'UPDATE_YOUTUBECONFIG_SUCCESS'
export const UPDATE_YOUTUBECONFIG_ERROR = 'UPDATE_YOUTUBECONFIG_ERROR'
export const GET_YOUTUBECONFIG_SUCCESS = 'GET_YOUTUBECONFIG_SUCCESS'
export const GET_YOUTUBECONFIG_ERROR = 'GET_YOUTUBECONFIG_ERROR'


export const UPDATE_TELEGRAMCONFIG_SUCCESS = 'UPDATE_TELEGRAMCONFIG_SUCCESS'
export const UPDATE_TELEGRAMCONFIG_ERROR = 'UPDATE_TELEGRAMCONFIG_ERROR'
export const GET_TELEGRAMCONFIG_SUCCESS = 'GET_TELEGRAMCONFIG_SUCCESS'
export const GET_TELEGRAMCONFIG_ERROR = 'GET_TELEGRAMCONFIG_ERROR'


export const UPDATE_FOURSQUARECONFIG_SUCCESS = 'UPDATE_FOURSQUARECONFIG_SUCCESS'
export const UPDATE_FOURSQUARECONFIG_ERROR = 'UPDATE_FOURSQUARECONFIG_ERROR'
export const GET_FOURSQUARECONFIG_SUCCESS = 'GET_FOURSQUARECONFIG_SUCCESS'
export const GET_FOURSQUARECONFIG_ERROR = 'GET_FOURSQUARECONFIG_ERROR'


export const UPDATE_WHATSAPPCONFIG_SUCCESS = 'UPDATE_WHATSAPPCONFIG_SUCCESS'
export const UPDATE_WHATSAPPCONFIG_ERROR = 'UPDATE_WHATSAPPCONFIG_ERROR'
export const GET_WHATSAPPCONFIG_SUCCESS = 'GET_WHATSAPPCONFIG_SUCCESS'
export const GET_WHATSAPPCONFIG_ERROR = 'GET_WHATSAPPCONFIG_ERROR'

