export const SAVE_WATERMARK_SUCCESS = 'SAVE_WATERMARK_SUCCESS'
export const SAVE_WATERMARK_ERROR = 'SAVE_WATERMARK_ERROR'
export const GET_WATERMARK_SUCCESS = 'GET_WATERMARK_SUCCESS'
export const GET_WATERMARK_ERROR = 'GET_WATERMARK_ERROR'
